# Hospital overcapacity

In [1]:
import pandas as pd
import geopandas as gpd
import jenkspy
import matplotlib.pyplot as plt
%matplotlib inline
import json
import numpy as np
import altair as alt
import altair_latimes as lat
alt.themes.register('latimes', lat.theme)
alt.themes.enable('latimes')
pd.options.display.max_columns = 50
pd.options.display.max_rows = 1000
alt.data_transformers.disable_max_rows()

DataTransformerRegistry.enable('default')

### Get state hospital utilization reports

In [15]:
before = pd.read_csv('../hospitals/output/hospital_utilization.csv', dtype={'fac_no':str})

In [16]:
before.head()

,fac_no,fac_name,fac_city,county,license_no,fac_zip,icu_beds,tot_lic_beds
0,106010735,ALAMEDA HOSPITAL,ALAMEDA,Alameda,140000002,94501,0,247
1,106010739,ALTA BATES SUMMIT MEDICAL CENTER-ALTA BATES CA...,BERKELEY,Alameda,140000004,94705,16,339
2,106010776,UCSF BENIOFF CHILDREN'S HOSPITAL OAKLAND,OAKLAND,Alameda,140000015,94609,23,223
3,106010811,FAIRMONT HOSPITAL,SAN LEANDRO,Alameda,140000046,94578,0,159
4,106010844,ALTA BATES SUMMIT MEDICAL CENTER-HERRICK CAMPUS,BERKELEY,Alameda,140000004,94704,0,68

### Get latest hospital capacity report from HHS

In [19]:
current = pd.read_csv('output/current_ca.csv')

In [20]:
current.head()

,hospital,hospital_subtype,ccn,week,county,fips,total_covid_icu_patients,total_available_adult_icu_beds,pct_occupied_adult_icu_beds,total_covid_patients,all_patients,covid_patients_share
0,Barstow Community Hospital,Short Term,050298,2020-12-25,San Bernardino,71,9.0,-1.0,1.11,46.0,44.0,1.05
1,Community Hospital of Huntington Park,Short Term,050091,2020-12-25,Los Angeles,37,9.0,0.0,1.00,45.0,49.0,0.92
2,Kaiser Foundation Hospital - Downey,Short Term,050139,2020-12-25,Los Angeles,37,43.0,1.0,0.98,230.0,262.0,0.88
3,Kaiser Foundation Hospital - Baldwin Park,Short Term,050723,2020-12-25,Los Angeles,37,26.0,0.0,1.00,161.0,188.0,0.86
4,Desert Valley Hospital,Short Term,050709,2020-12-25,San Bernardino,71,22.0,0.0,1.00,101.0,120.0,0.84