# Historical hurricane tracks: 1852-2018

In [1]:
import pandas as pd
import psycopg2 as pg
import matplotlib as mpl
import geopandas as gpd
import descartes
import geojson
import json

### Storm data scraped from [NOAA's Esri API](https://coast.noaa.gov/arcgis/rest/services/Hurricanes/AllHurricanes/MapServer/0)

In [2]:
canes_big = gpd.read_file('/Users/mhustiles/Desktop/data/GIS/hurricanes/cat_3-5-hurricanes_small_scale/canes_3_5_smallscale.geojson', index_col='2')

In [3]:
canes_sml = gpd.read_file('/Users/mhustiles/Desktop/data/GIS/hurricanes/cat_1-2-hurricanes_small_scale/cat12smallscale.geojson', index_col='2')

In [4]:
frames = [canes_sml, canes_big]
noaa_canes = pd.concat(frames)
noaa_canes.set_index('Display_StormName', inplace=True)

In [5]:
noaa_canes.head()

,STORMID,ObjectId,SaffirSimpsonScale,Shape.STLength(),NormalizedMSW,BeginObservationTime,BEGINLAT,BEGINLON,MinPressure,BASIN,DateAndTime,Display_NormalizedMSW,Display_Date,Display_MinPressure,Display_DateAndTime,SegmentOrder,OBJECTID_1,geometry
Display_StormName,,,,,,,,,,,,,,,,,,
BERTHA 1984,1984244N13319,230107,TD,141214.502946,25,1800,13.3,-42.2,1009.0,NA,08/30/1984 18,25.0,"Aug 30, 1984",1009.0,"Aug 30, 1984 18z",98170,8358608,LINESTRING (-42.20000000021429 13.299999999838...
MINDULLE 2004,2004174N14146,301411,TD,222227.491649,30,0,33.0417,124.525,1000.0,WP,07/04/2004 00,30.0,"Jul 04, 2004",1000.0,"Jul 04, 2004 00z",166430,8358609,LINESTRING (124.524999999709 33.04170000020529...
NATHAN 2015,2015068S12151,334879,NR,60163.859257,-1,0,-12.8,128.5,-1.0,SP,03/26/2015 00,-1.0,"Mar 26, 2015",-1.0,"Mar 26, 2015 00z",198886,8358610,LINESTRING (128.4999999996797 -12.800000000367...
TIM 1994,1994186N09139,265100,H4,165939.291079,120,0,20.85,123.475,-1.0,WP,07/10/1994 00,120.0,"Jul 10, 1994",-1.0,"Jul 10, 1994 00z",131174,8358611,LINESTRING (123.4750000000049 20.8500000001461...
DAPHNE 1991,1991046S18150,252917,TD,133583.388900,15,0,-18.6,136.8,-1.0,SP,02/19/1991 00,15.0,"Feb 19, 1991",-1.0,"Feb 19, 1991 00z",119440,8358612,LINESTRING (136.7999999998219 -18.600000000185...

### Another data source for hurricanes

In [6]:
# ! wget ftp://eclipse.ncdc.noaa.gov/pub/ibtracs/v03r10/all/csv/Allstorms.ibtracs_all.v03r10.csv.gz  -P /Users/mhustiles/Desktop/data/GIS/hurricanes/

In [7]:
# ! gunzip /Users/mhustiles/Desktop/data/GIS/hurricanes/Allstorms.ibtracs_all.v03r10.csv.gz

In [8]:
hurricanes = pd.read_csv('/Users/mhustiles/Desktop/data/GIS/hurricanes/Allstorms.ibtracs_all.v03r10.csv',
                 parse_dates=['ISO_time'], usecols=range(12),
                 skiprows=[0, 2], na_values=[-999, 'NOT NAMED'], index_col=1)
hurricanes.tail()

,Serial_Num,Num,Basin,Sub_basin,Name,ISO_time,Nature,Latitude,Longitude,Wind(WMO),Pres(WMO)
Season,,,,,,,,,,,
2017,2017161N13119,2,WP,MM,MERBOK,2017-06-12 06:00:00,TS,21.2,114.5,50.0,990.0
2017,2017161N13119,2,WP,MM,MERBOK,2017-06-12 12:00:00,TS,22.0,114.4,55.0,985.0
2017,2017161N13119,2,WP,MM,MERBOK,2017-06-12 18:00:00,TS,22.9,114.6,45.0,994.0
2017,2017161N13119,2,WP,MM,MERBOK,2017-06-13 00:00:00,TS,24.0,115.0,0.0,1002.0
2017,2017161N13119,2,WP,MM,MERBOK,2017-06-13 06:00:00,TS,25.5,115.7,0.0,1004.0

### Clean up column names for both datasets

In [9]:
hurricanes.columns = hurricanes.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
noaa_canes.columns = noaa_canes.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')

In [10]:
noaa_canes.tail()

,stormid,objectid,saffirsimpsonscale,shape.stlength,normalizedmsw,beginobservationtime,beginlat,beginlon,minpressure,basin,dateandtime,display_normalizedmsw,display_date,display_minpressure,display_dateandtime,segmentorder,objectid_1,geometry
Display_StormName,,,,,,,,,,,,,,,,,,
OLAF 2005,2005041S13181,304209,NR,24977.986012,-1,1200,-10.6,-178.6,-1.0,SP,02/11/2005 12,-1.0,"Feb 11, 2005",-1.0,"Feb 11, 2005 12z",169091,8458721,LINESTRING (-178.6000000001917 -10.59999999999...
UNNAMED 1959,1959247N13266,138700,H1,136956.376006,75,1800,17.1,-102.6,-999.0,EP,09/05/1959 18,75.0,"Sep 05, 1959",-999.0,"Sep 05, 1959 18z",38542,8458722,LINESTRING (-102.600000000091 17.1000000000409...
SEBASTIEN 1995,1995294N14306,270565,TS,138120.557345,50,0,20.9,-59.5,1001.0,NA,10/23/1995 00,50.0,"Oct 23, 1995",1001.0,"Oct 23, 1995 00z",136515,8458723,LINESTRING (-59.500000000002 20.89999999983421...
ELSIE 1989,1989286N14137,248219,TD,134975.673120,20,0,14.0,137.0,-1.0,WP,10/13/1989 00,20.0,"Oct 13, 1989",-1.0,"Oct 13, 1989 00z",115004,8458724,LINESTRING (137.0000000001934 14.0000000003358...
DOUG 1991,1991219N25165,254204,TD,91326.415510,20,1200,25.1,164.45,-1.0,WP,08/07/1991 12,20.0,"Aug 07, 1991",-1.0,"Aug 07, 1991 12z",120637,8458725,LINESTRING (164.4500000004147 25.0999999996925...

In [48]:
katrina = noaa_canes.loc['KATRINA 2005']

In [33]:
katrina = katrina.sort_values('dateandtime', ascending=False)

In [49]:
katrina_rita = noaa_canes.loc[['KATRINA 2005', 'RITA 2005'], ['normalizedmsw', 'dateandtime', 'basin']]

In [43]:
katrina.iloc[1:25]

,stormid,objectid,saffirsimpsonscale,shape.stlength,normalizedmsw,beginobservationtime,beginlat,beginlon,minpressure,basin,dateandtime,display_normalizedmsw,display_date,display_minpressure,display_dateandtime,segmentorder,objectid_1,geometry
Display_StormName,,,,,,,,,,,,,,,,,,
KATRINA 2005,2005236N23285,305700,ET,18.322424,25,600,40.1,-82.9,996.0,NA,08/31/2005 06,25.0,"Aug 31, 2005",996.0,"Aug 31, 2005 06z",170506,8489302,LINESTRING (-82.90000000033795 40.100000000259...
KATRINA 2005,2005236N23285,305699,ET,343528.687737,30,0,38.6,-85.3,994.0,NA,08/31/2005 00,30.0,"Aug 31, 2005",994.0,"Aug 31, 2005 00z",170505,8461309,LINESTRING (-85.30000000030331 38.600000000287...
KATRINA 2005,2005236N23285,305699,ET,343528.687737,30,0,38.6,-85.3,994.0,NA,08/31/2005 00,30.0,"Aug 31, 2005",994.0,"Aug 31, 2005 00z",170505,8461309,LINESTRING (-85.30000000030331 38.600000000287...
KATRINA 2005,2005236N23285,305698,TD,294331.863612,30,1800,37.0,-87.0,990.0,NA,08/30/2005 18,30.0,"Aug 30, 2005",990.0,"Aug 30, 2005 18z",170504,8493979,LINESTRING (-86.99999999986703 37.000000000354...
KATRINA 2005,2005236N23285,305698,TD,294331.863612,30,1800,37.0,-87.0,990.0,NA,08/30/2005 18,30.0,"Aug 30, 2005",990.0,"Aug 30, 2005 18z",170504,8493979,LINESTRING (-86.99999999986703 37.000000000354...
KATRINA 2005,2005236N23285,305697,TD,223137.229322,30,1200,35.6,-88.0,985.0,NA,08/30/2005 12,30.0,"Aug 30, 2005",985.0,"Aug 30, 2005 12z",170503,8563195,LINESTRING (-87.99999999992747 35.599999999696...
KATRINA 2005,2005236N23285,305697,TD,223137.229322,30,1200,35.6,-88.0,985.0,NA,08/30/2005 12,30.0,"Aug 30, 2005",985.0,"Aug 30, 2005 12z",170503,8563195,LINESTRING (-87.99999999992747 35.599999999696...
KATRINA 2005,2005236N23285,305696,TS,214164.719650,40,600,34.1,-88.6,978.0,NA,08/30/2005 06,40.0,"Aug 30, 2005",978.0,"Aug 30, 2005 06z",170502,8556921,LINESTRING (-88.60000000014338 34.100000000177...
KATRINA 2005,2005236N23285,305696,TS,214164.719650,40,600,34.1,-88.6,978.0,NA,08/30/2005 06,40.0,"Aug 30, 2005",978.0,"Aug 30, 2005 06z",170502,8556921,LINESTRING (-88.60000000014338 34.100000000177...
KATRINA 2005,2005236N23285,305695,TS,207511.273946,50,0,32.6,-89.1,961.0,NA,08/30/2005 00,50.0,"Aug 30, 2005",961.0,"Aug 30, 2005 00z",170501,8413412,LINESTRING (-89.10000000017359 32.600000000256...
KATRINA 2005,2005236N23285,305695,TS,207511.273946,50,0,32.6,-89.1,961.0,NA,08/30/2005 00,50.0,"Aug 30, 2005",961.0,"Aug 30, 2005 00z",170501,8413412,LINESTRING (-89.10000000017359 32.600000000256...
KATRINA 2005,2005236N23285,305694,H1,204314.936221,80,1800,31.1,-89.6,948.0,NA,08/29/2005 18,80.0,"Aug 29, 2005",948.0,"Aug 29, 2005 18z",170500,8561637,LINESTRING (-89.60000000020381 31.099999999972...
KATRINA 2005,2005236N23285,305694,H1,204314.936221,80,1800,31.1,-89.6,948.0,NA,08/29/2005 18,80.0,"Aug 29, 2005",948.0,"Aug 29, 2005 18z",170500,8561637,LINESTRING (-89.60000000020381 31.099999999972...
KATRINA 2005,2005236N23285,305693,H3,116458.896900,105,1445,30.2,-89.6,928.0,NA,08/29/2005 14,105.0,"Aug 29, 2005",928.0,"Aug 29, 2005 14z",170499,8383232,LINESTRING (-89.60000000020381 30.199999999892...
KATRINA 2005,2005236N23285,305693,H3,116458.896900,105,1445,30.2,-89.6,928.0,NA,08/29/2005 14,105.0,"Aug 29, 2005",928.0,"Aug 29, 2005 14z",170499,8383232,LINESTRING (-89.60000000020381 30.199999999892...
KATRINA 2005,2005236N23285,305692,H3,89843.910400,110,1200,29.5,-89.6,923.0,NA,08/29/2005 12,110.0,"Aug 29, 2005",923.0,"Aug 29, 2005 12z",170498,8429705,LINESTRING (-89.60000000020381 29.499999999755...
KATRINA 2005,2005236N23285,305692,H3,89843.910400,110,1200,29.5,-89.6,923.0,NA,08/29/2005 12,110.0,"Aug 29, 2005",923.0,"Aug 29, 2005 12z",170498,8429705,LINESTRING (-89.60000000020381 29.499999999755...
KATRINA 2005,2005236N23285,305691,H3,25555.054700,110,1110,29.3,-89.6,920.0,NA,08/29/2005 11,110.0,"Aug 29, 2005",920.0,"Aug 29, 2005 11z",170497,8468902,LINESTRING (-89.60000000020381 29.300000000123...
KATRINA 2005,2005236N23285,305691,H3,25555.054700,110,1110,29.3,-89.6,920.0,NA,08/29/2005 11,110.0,"Aug 29, 2005",920.0,"Aug 29, 2005 11z",170497,8468902,LINESTRING (-89.60000000020381 29.300000000123...
KATRINA 2005,2005236N23285,305690,H4,139672.311600,125,600,28.2,-89.6,913.0,NA,08/29/2005 06,125.0,"Aug 29, 2005",913.0,"Aug 29, 2005 06z",170496,8534217,LINESTRING (-89.60000000020381 28.200000000366...
KATRINA 2005,2005236N23285,305690,H4,139672.311600,125,600,28.2,-89.6,913.0,NA,08/29/2005 06,125.0,"Aug 29, 2005",913.0,"Aug 29, 2005 06z",170496,8534217,LINESTRING (-89.60000000020381 28.200000000366...
KATRINA 2005,2005236N23285,305689,H5,133383.214568,140,0,27.2,-89.2,905.0,NA,08/29/2005 00,140.0,"Aug 29, 2005",905.0,"Aug 29, 2005 00z",170495,8533100,LINESTRING (-89.20000000035931 27.200000000009...
KATRINA 2005,2005236N23285,305689,H5,133383.214568,140,0,27.2,-89.2,905.0,NA,08/29/2005 00,140.0,"Aug 29, 2005",905.0,"Aug 29, 2005 00z",170495,8533100,LINESTRING (-89.20000000035931 27.200000000009...
KATRINA 2005,2005236N23285,305688,H5,130572.511753,150,1800,26.3,-88.6,902.0,NA,08/28/2005 18,150.0,"Aug 28, 2005",902.0,"Aug 28, 2005 18z",170494,8486737,LINESTRING (-88.60000000014338 26.299999999895...

In [50]:
katrina_rita.groupby('Display_StormName').agg({'normalizedmsw': 'max'}).sort_values('normalizedmsw', ascending=False)

                   normalizedmsw
Display_StormName
RITA 2005                    155
KATRINA 2005                 150

In [51]:
print("Our data has {0} rows and {1} columns".format(noaa_canes.shape[0], noaa_canes.shape[1]))

Our data has 693940 rows and 18 columns