# Los Angeles active businesses

### Load python tools

In [9]:
import pandas as pd
from urllib.request import urlopen 
import os
import glob
import requests
import matplotlib
import numpy as np
from altair import datum
import altair as alt
import altair_latimes as lat
from sodapy import Socrata
alt.themes.register('latimes', lat.theme)
alt.themes.enable('latimes')
pd.options.display.max_columns = 50
pd.options.display.max_rows = 34000

### Read L.A. city database of active businesses

In [4]:
#https://dev.socrata.com/foundry/data.lacity.org/r4uk-afju

In [49]:
token = '2bOhwWJ7cVA7veVVCeHbFyWif'
username="matt.stiles@latimes.com"
password="datadesk!1"

client = Socrata('data.lacity.org', token, username, password)
results = client.get("6rrh-rzua", limit=2000000)
biz = pd.DataFrame.from_records(results)

In [50]:
biz.columns = biz.columns.str.strip().str.lower().str.replace(' ', '_')\
    .str.replace('(', '').str.replace(')', '').str.replace('-','_').str.replace('_&_','_')

In [51]:
biz.head()

,location_account,business_name,street_address,city,zip_code,location_description,naics,primary_naics_description,council_district,location_start_date,location_1,:@computed_region_qz3q_ghft,:@computed_region_kqwf_mjcx,:@computed_region_k96s_3jcv,:@computed_region_tatf_ua23,:@computed_region_2dna_qi2s,mailing_address,mailing_city,mailing_zip_code,:@computed_region_ur2y_g4cx,dba_name
0,0000000108-0001-3,PALACE OF VENICE GUEST HOME /C,1727 CRENSHAW BLVD,LOS ANGELES,90019-6037,1727 CRENSHAW 90019-6037,721310,Rooming & boarding houses,10,1991-05-15T00:00:00.000,"{'latitude': '34.0425', 'longitude': '-118.3295'}",23080,12,648,1105,19,NaN,NaN,NaN,NaN,NaN
1,0000000115-0001-3,VINCENZO LABELLA,521 SWARTHMORE AVENUE,PACIFIC PALISADES,90272-4350,521 SWARTHMORE 90272-4350,561500,Travel arrangement & reservation services,11,1990-01-01T00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,521 SWARTHMORE AVENUE,PACIFIC PALISADES,90272-4350,NaN,NaN
2,0000000121-0001-9,WILCARE ECONOMIC DEVELOPMENT CORPORATION,9911 AVALON BLVD,LOS ANGELES,90003-4805,9911 AVALON 90003-4805,721310,Rooming & boarding houses,8,1999-01-01T00:00:00.000,"{'latitude': '33.9463', 'longitude': '-118.2651'}",22351,14,806,1176,45,448 E 99TH STREET,LOS ANGELES,90003-4804,7,NaN
3,0000000132-0001-7,CARLOS ANGEL,1221 W 7TH STREET SUITE #N-407,LOS ANGELES,90017-2689,1221 7TH 90017-2689,561300,Employment services,1,1999-07-01T00:00:00.000,"{'latitude': '34.0518', 'longitude': '-118.2665'}",23078,11,564,1378,76,NaN,NaN,NaN,54,NaN
4,0000000133-0001-1,A A OFICINA CENTRAL HISPANA DE LOS ANGELES /C,4917 S BROADWAY,LOS ANGELES,90037-3211,4917 BROADWAY 90037-3211,611000,"Educational services (including schools, colle...",9,1991-01-01T00:00:00.000,"{'latitude': '33.9981', 'longitude': '-118.2783'}",23668,13,737,655,NaN,2607 VAN BUREN PLACE,LOS ANGELES,90007-2129,7,NaN

In [ ]:
biz['location_end_date'] = pd.to_datetime(biz['location_end_date'], errors='coerce')
biz['location_start_date'] = pd.to_datetime(biz['location_start_date'], errors='coerce')

In [ ]:
biz['end_month'] = biz['location_end_date'].dt.month.astype(str)
biz['end_year'] = biz['location_end_date'].dt.year.astype(str)

In [ ]:
biz.sort_values(by='location_end_date', ascending=False).head(10)

In [48]:
biz.groupby(['location_end_date']).agg('size').reset_index(name='closures')

      location_end_date  closures
0            1943-02-01         1
1            1958-01-01         1
2            1969-12-31         1
3            1970-09-15         1
4            1970-12-31         1
5            1972-12-22         1
6            1972-12-30         1
7            1973-12-31         1
8            1974-02-13         1
9            1975-01-01         1
10           1975-01-23         1
11           1975-09-30         1
12           1975-12-30         1
13           1976-01-09         1
14           1976-01-23         1
15           1976-02-06         1
16           1976-03-08         1
17           1976-04-15         1
18           1976-06-21         1
19           1976-07-12         1
20           1976-07-18         1
21           1976-12-31         2
22           1977-03-30         1
23           1977-04-01         1
24           1977-05-08         1
25           1977-05-31         1
26           1977-06-01         2
27           1977-07-01         1
28           1977-07-14         1
29           1977-07-18         1
30           1977-07-29         1
31           1977-07-30         5
32           1977-08-01         1
33           1977-08-26         1
34           1977-09-01         3
35           1977-09-02         1
36           1977-09-06         2
37           1977-10-21         1
38           1977-10-30         1
39           1977-11-14         1
40           1977-12-30        11
41           1977-12-31         2
42           1978-01-31         1
43           1978-04-01         1
44           1978-05-31         1
45           1978-06-01         1
46           1978-06-30         1
47           1978-07-01         1
48           1978-08-07         1
49           1978-09-02         2
50           1978-09-18         1
51           1978-09-30         3
52           1978-10-01         2
53           1978-10-30         3
54           1978-12-01         1
55           1978-12-18         1
56           1978-12-30         7
57           1978-12-31         9
58           1979-01-01         1
59           1979-01-30         1
60           1979-01-31         1
61           1979-02-16         1
62           1979-02-28         1
63           1979-03-01         1
64           1979-03-31         1
65           1979-04-06         1
66           1979-04-30         2
67           1979-05-30         1
68           1979-07-30         1
69           1979-08-09         1
70           1979-08-19         1
71           1979-08-31         1
72           1979-11-01         2
73           1979-11-22         1
74           1979-11-27         1
75           1979-12-30         9
76           1979-12-31        11
77           1980-01-01         9
78           1980-01-26         1
79           1980-01-30         1
80           1980-02-01         1
81           1980-02-28         1
82           1980-05-15         1
83           1980-05-20         1
84           1980-05-30         1
85           1980-06-01         1
86           1980-06-09         1
87           1980-06-30         3
88           1980-07-01        67
89           1980-07-16         1
90           1980-07-30         1
91           1980-07-31         1
92           1980-09-01         1
93           1980-09-30         2
94           1980-10-03         1
95           1980-10-25         1
96           1980-11-03         1
97           1980-11-15         1
98           1980-11-30         1
99           1980-12-01         2
100          1980-12-05         1
101          1980-12-30       167
102          1980-12-31       176
103          1981-01-01         1
104          1981-01-30         2
105          1981-02-09         1
106          1981-02-20         1
107          1981-02-28         1
108          1981-03-06         1
109          1981-03-13         1
110          1981-03-30         2
111          1981-04-30         1
112          1981-05-01         1
113          1981-06-01         1
114          1981-06-19         1
115          1981-06-20         1
116          1981-06-30         3
117          1981-07-13         1
118          1981-07-31         3
119          1981-08-01         1
120          1981-10-01         2
121          1981-10-30         5
122          1981-11-01         1
123          1981-11-30         2
124          1981-12-11         1
125          1981-12-15         1
126          1981-12-24         1
127          1981-12-30        16
128          1981-12-31        14
129          1982-01-01         5
130          1982-01-02         1
131          1982-01-30         2
132          1982-02-11         1
133          1982-02-17         1
134          1982-02-28         1
135          1982-03-30         2
136          1982-03-31         1
137          1982-04-01         1
138          1982-04-30         5
139          1982-05-16         1
140          1982-05-31         1
141          1982-06-01         1
142          1982-06-19         1
143          1982-06-30         3
144          1982-07-01         3
145          1982-07-12         1
146          1982-07-18         1
147          1982-07-26         1
148          1982-07-30         1
149          1982-07-31         3
150          1982-09-01         1
151          1982-09-14         1
152          1982-09-15         1
153          1982-09-30         3
154          1982-10-01         2
155          1982-10-26         1
156          1982-10-30         1
157          1982-11-01         1
158          1982-11-30         3
159          1982-12-03         1
160          1982-12-11         1
161          1982-12-30        21
162          1982-12-31        12
163          1983-01-01         4
164          1983-01-10         1
165          1983-01-30         5
166          1983-02-15         1
167          1983-02-28         2
168          1983-03-01         1
169          1983-03-22         1
170          1983-03-24         1
171          1983-03-28         1
172          1983-03-31         2
173          1983-04-01         1
174          1983-04-09         1
175          1983-04-13         1
176          1983-04-30         3
177          1983-05-11         1
178          1983-06-01         2
179          1983-06-20         1
180          1983-06-30         2
181          1983-07-18         1
182          1983-07-30         2
183          1983-07-31         1
184          1983-08-01         2
185          1983-08-08         2
186          1983-08-24         1
187          1983-08-26         1
188          1983-08-30         5
189          1983-09-01         1
190          1983-09-28         1
191          1983-09-30         3
192          1983-10-30         2
193          1983-10-31         2
194          1983-11-01         1
195          1983-11-14         1
196          1983-11-15         1
197          1983-11-30         3
198          1983-12-01         2
199          1983-12-30        41
200          1983-12-31        17
201          1984-01-01         4
202          1984-01-30         4
203          1984-01-31         1
204          1984-02-28         3
205          1984-03-01         1
206          1984-03-30         1
207          1984-03-31         1
208          1984-04-01         1
209          1984-04-07         1
210          1984-04-16         1
211          1984-04-30         3
212          1984-05-07         2
213          1984-05-16         1
214          1984-05-21         3
215          1984-05-28         1
216          1984-05-30         1
217          1984-06-04         1
218          1984-06-11         2
219          1984-06-12         1
220          1984-06-18         1
221          1984-06-22         1
222          1984-06-24         1
223          1984-06-25         1
224          1984-06-29         1
225          1984-06-30         6
226          1984-07-01         2
227          1984-07-26         1
228          1984-07-30         2
229          1984-08-01         2
230          1984-08-06         1
231          1984-08-20         1
232          1984-08-25         1
233          1984-08-31         1
234          1984-09-01         1
235          1984-09-10         2
236          1984-09-16         1
237          1984-09-17         2
238          1984-09-24         1
239          1984-09-30         4
240          1984-10-01         2
241          1984-10-08         2
242          1984-10-15         1
243          1984-10-22         1
244          1984-10-28         1
245          1984-10-29         1
246          1984-10-31         3
247          1984-11-02         1
248          1984-11-05         1
249          1984-11-15         1
250          1984-11-25         1
251          1984-11-30         2
252          1984-12-01         1
253          1984-12-07         1
254          1984-12-12         1
255          1984-12-13         1
256          1984-12-26         1
257          1984-12-28         1
258          1984-12-30        45
259          1984-12-31        20
260          1985-01-01         4
261          1985-01-03         1
262          1985-01-08         1
263          1985-01-25         1
264          1985-01-30         2
265          1985-01-31         1
266          1985-02-02         2
267          1985-02-04         3
268          1985-02-05         1
269          1985-02-25         1
270          1985-03-01         1
271          1985-03-02         2
272          1985-03-15         1
273          1985-03-24         1
274          1985-04-01         2
275          1985-04-13         2
276          1985-04-20         1
277          1985-04-28         1
278          1985-04-30         1
279          1985-05-01         2
280          1985-05-03         2
281          1985-05-05         1
282          1985-05-06         1
283          1985-05-18         1
284          1985-05-30         2
285          1985-05-31         1
286          1985-06-01         2
287          1985-06-03         2
288          1985-06-13         1
289          1985-06-16         1
290          1985-06-17         1
291          1985-06-30         7
292          1985-07-02         1
293          1985-07-06         1
294          1985-07-07         2
295          1985-07-17         1
296          1985-07-20         2
297          1985-07-22         2
298          1985-07-30         1
299          1985-07-31         1
300          1985-08-16         1
301          1985-08-19         1
302          1985-08-27         1
303          1985-08-30         1
304          1985-08-31         2
305          1985-09-01         1
306          1985-09-02         1
307          1985-09-08         1
308          1985-09-15         1
309          1985-09-16         2
310          1985-09-30         2
311          1985-10-01         1
312          1985-10-10         1
313          1985-10-16         1
314          1985-10-21         1
315          1985-10-30         1
316          1985-11-03         1
317          1985-11-13         1
318          1985-11-15         1
319          1985-11-25         1
320          1985-11-26         1
321          1985-11-30         2
322          1985-12-01         1
323          1985-12-02         1
324          1985-12-11         1
325          1985-12-21         1
326          1985-12-30        39
327          1985-12-31        52
328          1986-01-01         1
329          1986-01-02         1
330          1986-01-09         1
331          1986-01-30         2
332          1986-01-31         1
333          1986-02-28         3
334          1986-03-01         1
335          1986-03-11         1
336          1986-04-30         3
337          1986-05-01         3
338          1986-05-10         1
339          1986-05-12         1
340          1986-05-31         1
341          1986-06-09         1
342          1986-06-30         5
343          1986-07-01         1
344          1986-07-09         1
345          1986-07-15         1
346          1986-07-30         2
347          1986-08-15         2
348          1986-08-26         1
349          1986-08-30         3
350          1986-08-31         1
351          1986-09-01         1
352          1986-09-30         1
353          1986-10-01         1
354          1986-10-24         1
355          1986-10-30         1
356          1986-10-31         3
357          1986-11-01         1
358          1986-11-06         1
359          1986-11-16         1
360          1986-11-24         6
361          1986-11-30         4
362          1986-12-01         1
363          1986-12-05         1
364          1986-12-12         1
365          1986-12-27         1
366          1986-12-29         2
367          1986-12-30        44
368          1986-12-31        45
369          1987-01-01         8
370          1987-01-04         1
371          1987-01-05         1
372          1987-01-14         1
373          1987-01-23         1
374          1987-01-26         1
375          1987-02-01         3
376          1987-02-08         1
377          1987-02-16         1
378          1987-02-21         1
379          1987-02-28         2
380          1987-03-01         2
381          1987-03-05         1
382          1987-03-08         1
383          1987-03-30         1
384          1987-03-31         2
385          1987-04-01         2
386          1987-04-05         1
387          1987-04-06         1
388          1987-04-13         1
389          1987-04-24         1
390          1987-05-07         1
391          1987-05-19         1
392          1987-05-20         1
393          1987-05-27         2
394          1987-05-30         1
395          1987-06-01         2
396          1987-06-24         1
397          1987-06-25         1
398          1987-06-30         1
399          1987-07-01         3
400          1987-07-30         3
401          1987-08-01         3
402          1987-08-24         1
403          1987-08-27         1
404          1987-09-01         3
405          1987-09-02         1
406          1987-09-14         1
407          1987-09-17         1
408          1987-09-30         5
409          1987-10-08         2
410          1987-10-15         2
411          1987-10-19         1
412          1987-10-30         5
413          1987-10-31         4
414          1987-11-01         1
415          1987-11-05         1
416          1987-11-15         1
417          1987-11-20         1
418          1987-11-30         3
419          1987-12-01         8
420          1987-12-06         1
421          1987-12-10         1
422          1987-12-24         1
423          1987-12-30        25
424          1987-12-31        58
425          1988-01-01         7
426          1988-01-11         1
427          1988-01-24         1
428          1988-01-28         1
429          1988-01-30         1
430          1988-01-31         5
431          1988-02-01         3
432          1988-02-12         1
433          1988-02-15         1
434          1988-02-19         1
435          1988-02-23         1
436          1988-02-28         2
437          1988-03-01         1
438          1988-03-14         1
439          1988-03-27         6
440          1988-03-30         2
441          1988-04-01         5
442          1988-04-28         1
443          1988-04-30         1
444          1988-05-01         1
445          1988-05-04         1
446          1988-05-07         1
447          1988-05-30         1
448          1988-06-01         2
449          1988-06-14         1
450          1988-06-15         1
451          1988-06-30         1
452          1988-07-10         1
453          1988-07-12         1
454          1988-07-14         1
455          1988-07-15         1
456          1988-07-22         1
457          1988-07-25         1
458          1988-07-26         1
459          1988-07-30         2
460          1988-07-31         1
461          1988-08-01         4
462          1988-08-23         1
463          1988-08-26         1
464          1988-08-31         2
465          1988-09-01         5
466          1988-09-09         1
467          1988-09-11         1
468          1988-09-19         2
469          1988-09-29         1
470          1988-09-30         4
471          1988-10-01         3
472          1988-10-15         1
473          1988-10-30         2
474          1988-10-31         5
475          1988-11-01         2
476          1988-11-10         1
477          1988-11-30         4
478          1988-12-01         5
479          1988-12-09         1
480          1988-12-15         3
481          1988-12-19         1
482          1988-12-24         1
483          1988-12-30        24
484          1988-12-31        81
485          1989-01-01         8
486          1989-01-02         1
487          1989-01-03         1
488          1989-01-18         1
489          1989-01-20         1
490          1989-01-24         1
491          1989-01-30         1
492          1989-01-31         1
493          1989-02-01         1
494          1989-02-20         1
495          1989-02-28         3
496          1989-03-07         1
497          1989-03-13         1
498          1989-03-14         1
499          1989-03-15         1
500          1989-03-20         1
501          1989-03-31         5
502          1989-04-01         1
503          1989-04-05         1
504          1989-04-16         1
505          1989-04-18         1
506          1989-04-20         1
507          1989-04-28         1
508          1989-04-30         1
509          1989-05-01         2
510          1989-05-10         1
511          1989-05-13         1
512          1989-05-20         2
513          1989-05-21         1
514          1989-05-30         1
515          1989-05-31         1
516          1989-06-01         5
517          1989-06-16         1
518          1989-06-21         1
519          1989-06-30         6
520          1989-07-01         4
521          1989-07-26         1
522          1989-07-30         1
523          1989-07-31         1
524          1989-08-16         1
525          1989-08-18         1
526          1989-08-21         1
527          1989-08-30         2
528          1989-08-31         3
529          1989-09-01         2
530          1989-09-04         1
531          1989-09-07         1
532          1989-09-30         7
533          1989-10-01         4
534          1989-10-05         1
535          1989-10-13         1
536          1989-10-27         1
537          1989-10-30         2
538          1989-10-31         2
539          1989-11-01         4
540          1989-11-02         1
541          1989-11-06         1
542          1989-11-09         1
543          1989-11-17         4
544          1989-11-19         1
545          1989-11-20         2
546          1989-11-28         1
547          1989-11-30         1
548          1989-12-01         5
549          1989-12-03         1
550          1989-12-04         1
551          1989-12-14         1
552          1989-12-20         1
553          1989-12-28         1
554          1989-12-30        19
555          1989-12-31       156
556          1990-01-01        16
557          1990-01-03         1
558          1990-01-04         2
559          1990-01-05         1
560          1990-01-07         1
561          1990-01-12         3
562          1990-01-15         1
563          1990-01-31         4
564          1990-02-09         1
565          1990-02-15         1
566          1990-02-23         1
567          1990-02-26         1
568          1990-02-28         6
569          1990-03-01         2
570          1990-03-06         1
571          1990-03-16         1
572          1990-03-17         1
573          1990-03-19         2
574          1990-03-23         1
575          1990-03-30         3
576          1990-03-31         6
577          1990-04-01         3
578          1990-04-02         1
579          1990-04-04         1
580          1990-04-13         1
581          1990-04-17         1
582          1990-04-30         1
583          1990-05-01         6
584          1990-05-02         2
585          1990-05-04         1
586          1990-05-08         1